- hosts: all
  become: true
  tasks:
   - copy:
        content: "hello world"
        dest: /tmp/abc.txt
     notify: restart httpd
  handlers:
   - name: restart httpd
     service: 
        name: httpd
        state: restarted
        enabled: true

    
